name: SimPlug
main: com.simplug.Main
version: 1.0
api-version: 1.13
depend: [NBTAPI]
author: binary

commands:
  arena:
    description: TP to arena
    usage: /arena [player]

  sword:
    description: Add sword
    usage: /sword [player]

  dblock:
    description: Add diamond block with some ItemMeta
    usage: /dblock [player]

  gblock:
    description: Add gold block with some ItemMeta
    usage: /gblock [player]

  jitel:
    description: Add villager
    usage: /villager

  test:
    description: Test command
    usage: /test

  diamondnbt:
    description: Get diamond with NBT tag
    usage: /diamondnbt