name: SimPlug
main: com.simplug.Main
version: 1.0
api-version: 1.13

commands:
  arena:
    description: TP to arena
    usage: /arena [player]

  sword:
    description: Add sword
    usage: /sword [player]

  chest:
    description: Add chest
    usage: /chest [player]

  jitel:
    description: Add villager
    usage: /villager

  test:
    description: Test command
    usage: /test